version: '2'
services:
    slidy-app:
        image: slidy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://slidy-mysql:3306/slidy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    slidy-mysql:
        extends:
            file: mysql.yml
            service: slidy-mysql
